<?php

/**
 * @file
 * Update function for the block_visibility_conditions module.
 */

/**
 * Moved code to submodules.
 *
 * Enable the submodules for backwards compatibility.
 */
function block_visibility_conditions_update_9001() {
  /** @var \Drupal\Core\Extension\ModuleInstallerInterface $module_installer */
  $module_installer = \Drupal::service('module_installer');
  $module_installer->install([
    'block_visibility_conditions_node',
    'block_visibility_conditions_taxonomy',
  ]);
}
